# -*- coding: utf-8 -*-
import oracledb
from oracle_config import USER, PASSWORD, DSN

def recriar_tabela_usuarios():
    try:
        connection = oracledb.connect(user=USER, password=PASSWORD, dsn=DSN)
        cursor = connection.cursor()

        # Remove a tabela anterior se existir
        try:
            cursor.execute("DROP TABLE CS_USUARIOS")
        except:
            pass

        # Criando a tabela com a coluna NOME incluída
        sql = """
        CREATE TABLE CS_USUARIOS (
            id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            email VARCHAR2(100) UNIQUE NOT NULL,
            senha VARCHAR2(100) NOT NULL,
            nome VARCHAR2(100) NOT NULL,
            celular VARCHAR2(20),
            role VARCHAR2(50) NOT NULL,
            cliente_cnpj VARCHAR2(20),
            CONSTRAINT fk_usuario_cliente FOREIGN KEY (cliente_cnpj) REFERENCES CS_CLIENTES(CNPJ)
        )
        """
        cursor.execute(sql)
        print("Tabela CS_USUARIOS recriada com sucesso!")
        
        cursor.close()
        connection.close()
    except Exception as e:
        print(f"Erro ao recriar tabela: {e}")

if __name__ == "__main__":
    recriar_tabela_usuarios()