-- =====================================================================
-- Verificação do banco (somente consultas, não altera nada)
-- Execute com F5 (Executar Script) e confira a coluna SITUACAO. Onde aparecer FALTA, rode sql/estrutura_banco.sql.
-- =====================================================================

-- Tabelas do sistema
SELECT t.COLUMN_VALUE AS TABELA,
       CASE WHEN u.TABLE_NAME IS NOT NULL THEN 'OK' ELSE 'FALTA: rodar sql/estrutura_banco.sql' END AS SITUACAO
FROM TABLE(sys.odcivarchar2list(
        'CS_CLIENTES', 'CS_USUARIOS', 'CS_MUNICIPIOS', 'CS_FAZENDAS', 'CS_FAZENDAS_CLIMA', 'CS_ALERTAS',
        'CS_ALERTAS_PREDICAO', 'CS_EVENTOS', 'CS_EVENTOS_CLIMA', 'CS_EVENTOS_PREDICAO', 'CS_PIPELINE_LOGS',
        'CS_EQUIPAMENTOS_MODELOS', 'CS_EQUIPAMENTOS_MANUAIS', 'CS_EQUIPAMENTOS_ORIENTACOES', 'CS_EQUIPAMENTOS_SEGURADOS',
        'CS_LEITURAS_MEDIDOR', 'CS_MANUTENCOES_REALIZADAS', 'CS_ANEXOS', 'CS_SINISTROS',
        'CS_SCORE_MANUTENCAO_PROCEDIMENTOS', 'CS_SCORE_GESTAO', 'CS_NLP_REVISOES', 'CS_NLP_USO_IA')) t
LEFT JOIN USER_TABLES u ON u.TABLE_NAME = t.COLUMN_VALUE
ORDER BY 2 DESC, 1;

-- Colunas e índices acrescentados depois da criação original das tabelas
SELECT 'CS_ALERTAS.CHAVE_FOCO' AS ITEM,
       CASE WHEN COUNT(*) > 0 THEN 'OK' ELSE 'FALTA: rodar sql/estrutura_banco.sql' END AS SITUACAO
FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'CS_ALERTAS' AND COLUMN_NAME = 'CHAVE_FOCO'
UNION ALL
SELECT 'Índice único UX_CS_ALERTAS_CHAVE_FOCO',
       CASE WHEN COUNT(*) > 0 THEN 'OK' ELSE 'FALTA: rodar sql/estrutura_banco.sql' END
FROM USER_INDEXES WHERE INDEX_NAME = 'UX_CS_ALERTAS_CHAVE_FOCO'
UNION ALL
SELECT 'CS_FAZENDAS: colunas de relevo (4)',
       CASE WHEN COUNT(*) = 4 THEN 'OK' ELSE 'FALTA: rodar sql/estrutura_banco.sql' END
FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'CS_FAZENDAS'
  AND COLUMN_NAME IN ('ALTITUDE_M', 'DECLIVIDADE_PCT', 'CLASSE_RELEVO', 'ORIENTACAO_ENCOSTA')
UNION ALL
SELECT 'CS_CLIENTES: contato e responsável (15)',
       CASE WHEN COUNT(*) = 15 THEN 'OK' ELSE 'FALTA: rodar sql/estrutura_banco.sql' END
FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'CS_CLIENTES'
  AND COLUMN_NAME IN ('NOME_FANTASIA', 'INSCRICAO_ESTADUAL', 'ATIVIDADE_PRINCIPAL', 'TELEFONE', 'EMAIL', 'ENDERECO',
                      'MUNICIPIO', 'UF', 'CEP', 'RESPONSAVEL_NOME', 'RESPONSAVEL_CPF', 'RESPONSAVEL_CARGO',
                      'RESPONSAVEL_TELEFONE', 'RESPONSAVEL_EMAIL', 'DATA_ATUALIZACAO')
UNION ALL
SELECT 'CS_EQUIPAMENTOS_SEGURADOS: uso e tração (8)',
       CASE WHEN COUNT(*) = 8 THEN 'OK' ELSE 'FALTA: rodar sql/estrutura_banco.sql' END
FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'CS_EQUIPAMENTOS_SEGURADOS'
  AND COLUMN_NAME IN ('DATA_AQUISICAO', 'HORIMETRO_ATUAL', 'HODOMETRO_ATUAL', 'DATA_LEITURA', 'USO_MEDIO_HORAS_MES',
                      'USO_MEDIO_KM_MES', 'TIPO_OPERACAO', 'TIPO_TRACAO')
UNION ALL
SELECT 'CS_EVENTOS_PREDICAO: estatística das regras (4)',
       CASE WHEN COUNT(*) = 4 THEN 'OK' ELSE 'FALTA: rodar sql/estrutura_banco.sql' END
FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'CS_EVENTOS_PREDICAO'
  AND COLUMN_NAME IN ('PROBABILIDADE', 'CASOS', 'ORIGEM_REGRA', 'DATA_GERACAO')
UNION ALL
SELECT 'Manuais vinculados aos modelos',
       CASE WHEN COUNT(*) >= 2 THEN 'OK' ELSE 'FALTA: rodar sql/estrutura_banco.sql' END
FROM CS_EQUIPAMENTOS_MANUAIS
UNION ALL
SELECT 'Recomendações dos manuais',
       CASE WHEN COUNT(*) > 0 THEN 'OK' ELSE 'FALTA: rodar outputs/orientacoes/CS_EQUIPAMENTOS_ORIENTACOES.sql' END
FROM CS_EQUIPAMENTOS_ORIENTACOES;

-- Situação dos dados
SELECT 'Fazendas' AS ITEM, COUNT(*) AS TOTAL,
       SUM(CASE WHEN ALTITUDE_M IS NULL THEN 1 ELSE 0 END) AS SEM_RELEVO
FROM CS_FAZENDAS;

SELECT ORIGEM_ALERTA, COUNT(*) AS ALERTAS, MIN(DATA_HORA) AS PRIMEIRO, MAX(DATA_HORA) AS ULTIMO
FROM CS_ALERTAS
GROUP BY ORIGEM_ALERTA;

SELECT COUNT(*) AS HORAS_CLIMA, MIN(DATA_HORA) AS PRIMEIRA, MAX(DATA_HORA) AS ULTIMA
FROM CS_FAZENDAS_CLIMA;

-- Últimas execuções do pipeline
SELECT SCRIPT_NOME, STATUS, DATA_EXECUCAO_BR, REGISTROS_PROCESSADOS,
       DBMS_LOB.SUBSTR(MENSAGEM_RETORNO, 200, 1) AS MENSAGEM
FROM CS_PIPELINE_LOGS
ORDER BY DATA_EXECUCAO DESC
FETCH FIRST 10 ROWS ONLY;
